language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ngamenichaka/react-test -f ./client/Dockerfile.dev ./client #we use Dockerfile.dev because we have necessary to start test

script:
  - docker run -e CI=true ngamenichaka/react-test npm run test

after_success:
  - docker build -t ngamenichaka/multi-client ./client
  - docker build -t ngamenichaka/multi-nginx ./nginx
  - docker build -t ngamenichaka/multi-server ./server
  - docker build -t ngamenichaka/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push ngamenichaka/multi-client
  - docker push ngamenichaka/multi-nginx
  - docker push ngamenichaka/multi-server
  - docker push ngamenichaka/multi-worker
  deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-west-3
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-3-764796658196
    bucket_path: multi-docker
    on:
      branch: master
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
